[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elsa = "1.10.0"
itertools = "0.13.0"
ndarray = "0.16.1"
regex = "1.11.1"
